version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: intentkit_clean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  intent-api:
    image: crestalnetwork/intentkit:latest
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:senha123@db:5432/intentkit_clean
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
